### ISSUE TITLE
impossible to import 

### ISSUE THREAD

**Issue by averyfreeman** [eswann/bootsy#1]
Lack of access to default node library (?)
```
Module not found: Can't resolve 'perf_hooks' in 'C:\%PROJECT_FOLDER%\node_modules\bootsy\dist\util'
```

I just upgraded from node 14.17.6 to 14.18.1, hoping that would help.
I've tried installing `typescript @types/react @types/node` both locally and globally, 
I tried importing `perf_hooks` manually as `{ performance }`. 
I even went into the `bootsy/dist/util` folder, removed the `perf_hooks` import from `logging-util.js` and replaced the functions that called it with hilarious `console.log`s. 

Would like to try out `bootsy`, but so far this issue has been a brick wall.

**Comment by eswann** [comment]
Hey Avery, I'll take a look, thanks for the input! Is your code in Github somewhere so I can take a look?

**Comment by eswann** [comment]
Closing for lack of information. Please reopen if a demo is available.
